---
title: "Informal Sensitivity Analysis, Almond Profit"
author: "Juliet, Shale, & Sydney"
date: '2022-04-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

## Sensitivity Analysis

#### Read in almond data, input it into the `almond_anomaly()` function, and input the result into the `profit()` function

```{r}
# read in the climate data
data <- read.table("clim.txt", sep = " ", header = T)

# load in almond_anomaly.R function
source(here("almond_anomaly.R"))
source(here("profit.R"))

# calculate almond yield anomaly
almond_anom <- almond_anomaly(data = data)

# simple profit calculation based on almond anomaly
profit <- profit(df = almond_anom, acres = 5)

profit[[1]]
```

#### Vary the parameters `price` and `discount`

```{r}
# number of samples to generate for both parameters
n_samples = 300

deviation_price = 0.15 # $0.15 deviation in price
base_price = 2.00 # the base price value for almonds, this value will increase & decrease by 15 cents in the sensitivity analysis distribution
price = runif(min = base_price - deviation_price,
              max = base_price + deviation_price, 
              n = n_samples)

deviation_discount = 0.02 # 2% deviation in discount rate
base_discount = 0.12 # the base discount value for the price of almonds, this value will increase & decrease by 2% in the sensitivity analysis distribution
discount = runif(min = base_discount - deviation_discount,
                 max = base_discount + deviation_discount, 
                 n = n_samples)

parameters = cbind.data.frame(price, discount)

# results = running the function profit() on the parameter distributions we created, and using the almond_anom df and 5 for acres
# first remind R that the function needs to be sourced
source(here("Profit.R"))

results = parameters %>% 
  pmap(profit, df = almond_anom, acres = 5)

results[[1]]

# check that the length is the same number of rows as n_samples
length(results)

# now we can extract results from the list as above, subset with `[`
annual_profit = map_df(results,`[`, c("sum")) 

# and we can add the parameter values for each run
annual_profit_df = cbind.data.frame(annual_profit, parameters)
```

```{r}
# exploratory plots
ggplot(data = annual_profit_df, aes(x = price, y = sum)) +
  geom_point()

ggplot(data = annual_profit_df, aes(x = discount, y = sum)) +
  geom_point()
```

#### Save the graph that best represents the data

```{r}

ggplot(data = annual_profit_df, aes(x = discount, y = sum)) +
  geom_point() +
  theme_classic() +
  ggtitle("Discount Rate and Total Profit Anomaly \n for Almond Yield Anomalies 1989-2010") +
   xlab("Discount Rate (Percent)") + 
   ylab("Profit (US Dollars)") +
   theme(axis.title.x = element_text(color = "black", size = 11, face = "bold"),
         axis.text.x = element_text(face = "bold", color = "black", size = 10),
         axis.title.y = element_text(color = "black", size = 11, face = "bold"),
         axis.text.y = element_text(face = "bold", color = "black", size = 10),
         plot.title = element_text(color="black", size = 15, face = "bold", hjust = 0.5),
         panel.border = element_rect(colour = "black", fill = NA, size = 2)) +
  scale_y_continuous(breaks = seq(12000, 18000, by = 1000))

ggsave(filename = "discount_profit_plot.jpeg", plot = last_plot(), path = here())
```










